rainbow:
  kuzwlu:
    utils:
      log-dir: log
      #all black-list write-list
      bw-flag: all #black-list
      write-list:
        -java.lang
        -java.util
        -[Ljava.lang ()
        -[D (double[])
        -[F (float[])
        -[I (int[])
        -[J (long[])
        -[C (char[])
        -[B (byte[])
        -[Z (boolean[])
        -love.forte.common
        -love.forte.simbot
        -catcode
        -rainbow.kuzwlu.core.plugins.utils
        -rainbow.kuzwlu.pluginsBot
        -rainbow.kuzwlu.core.plugins.annotation
        -rainbow.kuzwlu.core.annotation.OnNudged
        -rainbow.kuzwlu.utils
        -rainbow.kuzwlu.config
        -java.io.PrintStream
        -System.out
        -java.time
        -org.json.JSONArray
        -org.json.JSONObject

      black-list:
        -java.lang.Thread
        -java.lang.Runtime
        -java.lang.reflect
        -java.net.URL
        -java.io.File
        -java.io.FileWriter
        -java.io.RandomAccessFile
        -rainbow.kuzwlu.core.plugins.compiler
        -rainbow.kuzwlu.core.plugins.enums
        -rainbow.kuzwlu.core.plugins.tool
        -rainbow.kuzwlu.utils.config
        -rainbow.kuzwlu.utils.exception
        -rainbow.kuzwlu.utils.config
        -System

    bot:
      admin-list:
        #-23396652
        -1726539504
      start-flag: true

#项目名称
spring:
  application:
    name: Rainbow-Bot
  main:
    banner-mode: off

#日志文件
logging:
  file:
    path: /Users/kuzwlu/Downloads/bot_log

simbot:
  core:
    # bot的账号与密码。
    bot-resource-type: BOTH
    #扫描包路径
    scan-package: rainbow.kuzwlu
  component:
    mirai:
      # mirai心跳周期. 过长会导致被服务器断开连接. 单位毫秒。
      heartbeat-period-millis: 60000
      # 每次心跳时等待结果的时间.一旦心跳超时, 整个网络服务将会重启 (将消耗约 1s). 除正在进行的任务 (如图片上传) 会被中断外, 事件和插件均不受影响.
      heartbeat-timeout-millis: 5000
      # 心跳失败后的第一次重连前的等待时间.
      first-reconnect-delay-millis: 5000
      # 使用协议类型。注，此值为枚举类 net.mamoe.mirai.utils.BotConfiguration.MiraiProtocol 的元素值，
      # 可选值为：ANDROID_PHONE、ANDROID_PAD、ANDROID_WATCH
      protocol: ANDROID_PHONE
      # 是否关闭mirai的bot logger
      no-bot-log: false
      # 关闭mirai网络日志
      no-network-log: false
      # mirai bot log切换使用simbot的log
      use-simbot-bot-log: true
      # mirai 网络log 切换使用simbot的log
      use-simbot-network-log: true
      # mirai配置自定义deviceInfoSeed的时候使用的随机种子。默认为1.
      device-info-seed: 1
      # mirai图片缓存策略，为枚举 love.forte.simbot.component.mirai.configuration.MiraiCacheType 的元素值，
      # 可选为 FILE、 MEMORY
      cache-type: FILE
      # 如果配置项 simbot.mirai.cacheType 的值为 FILE，此处为缓存文件的保存目录。为空时默认为系统临时文件夹。
      cache-directory:
      # 如果不为空，此处代表指定一个 deviceInfo 的 json文件路径。
      deviceInfo-file:
      # 选择是否输出mirai的deviceInfo文件信息。会生成在当前项目的根目录下。
      device-info-output: false
      # mirai提供的配置：Highway 通道上传图片, 语音, 文件等资源时的协程数量.
      highway-upload-coroutine-count:
      message:
        cache:
          enable: false
          priCapacity: 16
          priInitialCapacity: 16
          groCapacity: 128
          groInitialCapacity: 128
          priLoadFactor: 0.75
          groLoadFactor: 0.75

